### ISSUE TITLE
Error: /bin/bash: node: command not found

### ISSUE THREAD

**Issue by katopz** [seegno/primus-objc#13]
While I try to run testing I got 14 failed with this clues.
```shell
Test Case '-[SocketIOClientSpec spt_runExampleAtIndex:]' started.
2015-05-13 12:46:51.156 xctest[7464:696938] Error: /bin/bash: node: command not found
/Users/pirsquare/git/primus-objc/PrimusTests/Transformers/socket.IO/
``` 

And yes, I'm running and using node without any problem via my Mac terminal.
```shell
$ which node
/usr/local/bin/node
$ node -v
v0.12.2
```

I think I miss something here(noob alert), any help would be appreciated, I'm stuck for an hour already.

Thanks

**Comment by nunofgs** [comment]
The `node` library should be in your shell's $PATH.

We are launching the currently defined `$SHELL` in order to inherit the proper environment variables, as you can see [here](https://github.com/seegno/primus-objc/blob/master/PrimusTests/Transformers/TransformerBehaviorTest.m#L42), but in your case it doesn't seem to be working.

On your command-line, can you try the following?
```bash
$ /bin/bash
bash-3.2$ which node
```

As a quick workaround, change [this](https://github.com/seegno/primus-objc/blob/master/PrimusTests/Transformers/TransformerBehaviorTest.m#L26) line to `NSString *nodePath = @"/usr/local/bin/node";`

**Comment by katopz** [comment]
Hi @nunofgs

I got...
```shell
$ /bin/bash
bash-3.2$ which node
/usr/local/bin/node
```
And workaround is working, I'm happy now! 
so you can close this in case only me mess this up :)

Thanks!

**Comment by nunofgs** [comment]
It should work but I'll close for now. Please reopen as needed.
